on:
  issues:
    types:
      - published
  issue_comment:
    types:
      - created

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'issues'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number}}
          body: |
            Hey, welcome!
            Thank you for creating an issue. This is an automated response!
          reactions: '+1'
  pong:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'issue_comment' && contains(github.event.comment, 'ping')
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number}}
          body: |
            Pong!
